karoRecharge/urls.py
from django.urls import path
from . import views

app_name = 'karoRecharge'

urlpatterns = [
	# path('', views.homeView, name="homeURL"),
	path('recharge-plan', views.rechargePlanView, name='rechargePlanUrl'),
	path('recharge-plan/<slug>/',views.rechargePlanDetailView, name='rechargePlanDetailUrl'),
	
	#submit
	path('generate-recharge-plan', views.generateRechargePlan, name='generateRechargePlanUrl')


]

rechargeApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
      path('', include('karoRecharge.urls', namespace="websiteApp")),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

karoRecharge/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator
# from django.contrib.auth.models import User
from django.urls import reverse

STATUS_CHOICES = (
	('draft', 'Draft'),
	('published', 'Published'),
)

# Create your models here.
class rechargePlan(models.Model):
	#about servicex
    price = models.BigIntegerField(null=True, blank=True)
    slug = models.SlugField(null=True,blank=True)
    combo = models.TextField(null=True, blank=True)
    data_with_rollover = models.CharField(max_length=255, null=True, blank=True)
    sms_per_day = models.CharField(max_length=255, null=True, blank=True)
    local_std_and_roaming_calls = models.CharField(max_length=255, null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    
    def get_absolute_url(self):
        return reverse('karoRecharge:rechargePlanDetailUrl', args=[self.slug])
    
    def __str__(self):
        return str(self.price) or '--Name not provided--'
    class Meta:
        verbose_name_plural = 'Prepaid Recharge Plan List'


class Images(models.Model):
	file = models.FileField('File', upload_to='images/', null=True, blank=True)
	title = models.CharField(max_length=100, null=True, blank=True)
	description = models.CharField(max_length=250, null=True, blank=True)
	rechargePlan = models.OneToOneField(rechargePlan, related_name='imagesRP', on_delete=models.SET_NULL, blank=True, null=True)

	def __str__(self):
		return self.filename

	@property
	def filename(self):
		return self.file.name.rsplit('/', 1)[-1]

class generateCustomerRecharge(models.Model):
    customerName = models.CharField(max_length=256,null=True, blank=True)
    customerNumber = models.BigIntegerField(null=True, blank=True)
    customerPlan = models.OneToOneField(rechargePlan, related_name='customerPlanCMN', on_delete=models.CASCADE, null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    
    def __str__(self):
        return f"Number -- {self.customerNumber}" or '--Name not provided--'
    
    class Meta:
        verbose_name_plural = 'Generated recharge List : Customer Numbers'

 

karoRecharge/forms.py
from django import forms
from .models import *

#
class generateCustomerRechargeForm(forms.ModelForm):
	class Meta:
		model = generateCustomerRecharge
		fields = ('customerNumber','customerPlan',)

karoRecharge/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import *
from .forms import *

# Create your views here.
def rechargePlanView(request):
    rechargePlanList = rechargePlan.objects.filter(status='published')
    print('hi ' + str(rechargePlanList))
    context ={
        'rechargePlanList':rechargePlanList,
    }
    return render(request, 'plans.html', context)


#
def rechargePlanDetailView(request,slug):
    pageInst = get_object_or_404(rechargePlan, slug=slug)
    context = {
        'pageInst':pageInst,
        }
    return render(request, 'planDetail.html', context)

#
def generateRechargePlan(request):
    customerPlan = request.POST.get('customerPlan')
    rechargeInst = rechargePlan.objects.filter(price = customerPlan)
    if request.method == 'POST':
        formObj = generateCustomerRechargeForm(request.POST)
        print(formObj)
        if formObj.is_valid():
            cd = formObj.save(commit=False)
            cd.save()
            return HttpResponse('Recharge Successful')
        else:
            return HttpResponse('opppssssss')
    else:
        return HttpResponse('Wrong Number')

karoRecharge/templates/planDetail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Recharge Plan Detail</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, p { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #eee;
      }
      body {
      background: url("/uploads/media/default/0001/01/b5edc1bad4dc8c20291c8394527cb2c5b43ee13c.jpeg") no-repeat center;
      background-size: cover;
      }
      h1, h2 {
      text-transform: uppercase;
      font-weight: 400;
      }
      h2 {
      margin: 0 0 0 8px;
      }
      .main-block {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: 100%;
      padding: 25px;
      background: rgba(0, 0, 0, 0.5); 
      }
      .left-part, form {
      padding: 25px;
      }
      .left-part {
      text-align: center;
      }
      .fa-graduation-cap {
      font-size: 72px;
      }
      form {
      background: rgba(0, 0, 0, 0.7); 
      }
      .title {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
      }
      .info {
      display: flex;
      flex-direction: column;
      }
      input, select {
      padding: 5px;
      margin-bottom: 30px;
      background: transparent;
      border: none;
      border-bottom: 1px solid #eee;
      }
      input::placeholder {
      color: #eee;
      }
      option:focus {
      border: none;
      }
      option {
      background: black; 
      border: none;
      }
      .checkbox input {
      margin: 0 10px 0 0;
      vertical-align: middle;
      }
      .checkbox a {
      color: #26a9e0;
      }
      .checkbox a:hover {
      color: #85d6de;
      }
      .btn-item, button {
      padding: 10px 5px;
      margin-top: 20px;
      border-radius: 5px; 
      border: none;
      background: #26a9e0; 
      text-decoration: none;
      font-size: 15px;
      font-weight: 400;
      color: #fff;
      }
      .btn-item {
      display: inline-block;
      margin: 20px 5px 0;
      }
      button {
      width: 100%;
      }
      button:hover, .btn-item:hover {
      background: #85d6de;
      }
      @media (min-width: 568px) {
      html, body {
      height: 100%;
      }
      .main-block {
      flex-direction: row;
      height: calc(100% - 50px);
      }
      .left-part, form {
      flex: 1;
      height: auto;
      }
      }
    </style>
  </head>
  <body>
    <div class="main-block">
      <div class="left-part">
        <i class="fa fa-mobile-phone" style="font-size:48px;color:red"></i>
        <h1>Plan</h1>
        <p>{{pageInst.price}}</p>
        <p>{{pageInst.data_with_rollover}}</p>
        
      </div>
      <form action="{% url 'karoRecharge:generateRechargePlanUrl' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="title">
           
          <h2>Enter Mobile Number</h2>
        </div>
        <div class="info">
          <input type="hidden" name="customerPlan" placeholder="Full name" value="{{pageInst.pk}}">
          <input class="Number" type="number" name="customerNumber" placeholder="Enter Number" required>
          {% comment %}
          <!-- <input type="text" name="name" placeholder="Email"> -->
          <!-- <input type="text" name="name" placeholder="Phone number">
          <input type="password" name="name" placeholder="Password">
          <select>
            <option value="course-type" selected>Course type*</option>
            <option value="short-courses">Short courses</option>
            <option value="featured-courses">Featured courses</option>
            <option value="undergraduate">Undergraduate</option>
            <option value="diploma">Diploma</option>
            <option value="certificate">Certificate</option>
            <option value="masters-degree">Masters degree</option>
            <option value="postgraduate">Postgraduate</option>
          </select> -->
<!--          
        </div>
        <div class="checkbox">
          <input type="checkbox" name="checkbox"><span>I agree to the <a href="https://www.w3docs.com/privacy-policy">Privacy Poalicy for W3Docs.</a></span>
        </div> -->
        {% endcomment %}
        <button type="submit" href="/">Submit</button>
      </form>
    </div>
  </body>
</html>

karoRecharge/templates/plans.html
<html>
<head>
<title>
    Recharge Plan List
</title>
</head>
<body>

{% for i in rechargePlanList %}
<br>
price : {{i.price}}
<br>
combo  : {{i.combo|safe}}
<br>
{{i.data_with_rollover}}
<br>
{{i.sms_per_day}}
<br>
{{i.local_std_and_roaming_calls}}
<br>
<div class="text-center">
    <a href="{{i.get_absolute_url}}" type="button" class="btn btn-dark cont-on-main  text-white btn-sm">Know More</a>
</div>
{% endfor %}
</body>
</html>